kumuluzee:
  name: govorilne-ure
  version: 1.0.0
  env:
    name: dev

  datasources:
      - jndi-name: jdbc/KatalogDB
        connection-url: jdbc:postgresql://localhost:5432/govorilne_ure
        username: postgres
        password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/KatalogDB
      disk-space-health-check:
        threshold: 100000000
  security:
    keycloak:
      json: '{
                 "realm": "govorilne_ure",
                 "bearer-only": true,
                 "auth-server-url": "http://localhost:8082/auth",
                 "ssl-required": "external",
                 "resource": "govorilne_ure_api",
                 "confidential-port": 0
               }'
integrations:
  komnunikacijski-kanali:
    base-url: http://localhost:8081/v1
  zunanji-vir:
    base-url: date.nager.at/Api/v2/PublicHolidays